# Beat-by-beat edit plan for the Milgram voiceover.
# Each beat: (start_seconds, kind, arg, opts). A beat lasts until the next beat starts.
# kinds:
#   clip  arg="SRC:sec"         archival footage starting at sec (SRC in CLIPS)
#   img   arg="search query"    dark illustration / photo from image search
#   wiki  arg=key in WIKI       Wikimedia Commons file
#   gfx   arg=graphic name      programmatic graphic, opts carry props
#   word  arg="BIG TEXT"        kinetic red title (opts: small, bg, color)
#   type  arg="TEXT"            typewriter text (opts: sub, bg)
#   carousel arg="BIG"          game-select carousel item (opts: small, bg)
#   card  arg="Title"           chapter card (opts: label, num, icon)
#   black
# opts: grade (ink|red|color|sepia|cold|gray), motion (in|out|left|right|up|down|shake), sfx

CLIPS = {
    'MDE': 'milgram_doc_de.mp4',
    'EIC': 'eichmann_s6.mp4',
    'WAY': 'world_at_your_call.mp4',
    'NAR': 'narcotics_1967.mp4',
    'NUR': 'nuremberg_1950.ogv',
}

WIKI = {
    'milgram': 'File:Stanley Milgram 1974.jpg',
    'milgram_young': 'File:Stanley Milgram 1954.jpg',
    'ad': 'File:Milgram Experiment advertising.png',
    'yale': 'File:YaleOldCAmpus4936.JPG',
    'scream': 'File:Edvard Munch, 1893, The Scream, oil, tempera and pastel on cardboard, 91 x 73 cm, National Gallery of Norway.jpg',
}

B = [
 # ---------------- COLD OPEN ----------------
 (0.0,  'word', 'THIS MACHINE', {'bg': 'laser', 'sfx': 'impact'}),
 (0.55, 'clip', 'MDE:234.5', {'grade': 'red', 'motion': 'in'}),
 (1.5,  'clip', 'MDE:361', {'grade': 'ink'}),
 (2.9,  'gfx',  'counter', {'text': '26 / 40', 'sub': 'PEOPLE', 'sfx': 'hit'}),
 (4.7,  'clip', 'MDE:228', {'grade': 'ink', 'motion': 'in'}),
 (5.5,  'clip', 'MDE:619', {'grade': 'ink'}),
 (6.3,  'clip', 'MDE:505', {'grade': 'ink', 'motion': 'in'}),
 (7.3,  'word', 'KILLED A MAN', {'small': 'believing they might have', 'bg': 'MDE:600', 'sfx': 'boom'}),
 (9.3,  'type', 'NEW HAVEN, CONNECTICUT', {'sub': '1961', 'bg': 'img:New Haven Connecticut 1960s street black and white photo'}),
 (12.88,'clip', 'MDE:6', {'grade': 'ink', 'motion': 'in'}),
 (13.9, 'wiki', 'yale', {'grade': 'ink', 'motion': 'in'}),
 (14.9, 'wiki', 'milgram_young', {'grade': 'ink', 'motion': 'in'}),
 (16.5, 'type', 'STANLEY MILGRAM', {'sub': 'PSYCHOLOGIST · AGE 28', 'bg': 'wiki:milgram'}),
 (17.7, 'gfx',  'shockpanel', {'mode': 'reveal'}),
 (18.7, 'gfx',  'shockpanel', {'mode': 'cascade', 'sfx': 'clicks'}),
 (20.5, 'gfx',  'shockpanel', {'mode': 'zoomLast'}),
 (21.6, 'word', '450 VOLTS', {'bg': 'laser', 'sfx': 'shock'}),
 (24.28,'img',  '1960s men walking city street black and white photo', {'grade': 'ink', 'motion': 'left'}),
 (25.5, 'img',  'ordinary working men 1960s black and white portrait', {'grade': 'ink', 'motion': 'in'}),
 (26.9, 'clip', 'MDE:528', {'grade': 'ink'}),
 (27.9, 'gfx',  'shockpanel', {'mode': 'press3', 'sfx': 'clicks3'}),
 (29.1, 'clip', 'MDE:444', {'grade': 'red'}),
 (29.9, 'clip', 'MDE:534', {'grade': 'red', 'motion': 'shake', 'sfx': 'glitch'}),
 (32.0, 'word', 'STOP', {'small': 'every one of them said they would', 'color': 'white'}),
 (34.3, 'word', 'NONE DID', {'small': 'almost', 'bg': 'MDE:528', 'sfx': 'boom'}),
 (36.3, 'clip', 'MDE:247', {'grade': 'ink', 'motion': 'in'}),
 (37.4, 'clip', 'MDE:229', {'grade': 'red', 'motion': 'in'}),
 (39.0, 'img',  'man staring at his reflection in mirror dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (41.2, 'word', "YOU'RE WRONG", {'small': 'and why', 'bg': 'laser', 'sfx': 'glitch'}),
 (42.88,'clip', 'MDE:870', {'grade': 'ink', 'motion': 'in'}),
 (44.86,'word', '3 STUDIES', {'color': 'white', 'sfx': 'whoosh'}),
 (46.0, 'word', '3 DECADES', {'color': 'white', 'sfx': 'whoosh'}),
 (47.4, 'word', 'SAME RESULT', {'sfx': 'impact'}),
 (49.1, 'carousel', 'MILGRAM', {'small': '1963', 'bg': 'wiki:milgram'}),
 (51.3, 'carousel', 'HOFLING', {'small': '1966', 'bg': 'WAY:211'}),
 (53.9, 'carousel', 'BURGER', {'small': '2009', 'bg': 'MDE:870'}),
 (55.6, 'black', '', {}),
 # ---------------- THE EXPERIMENT ----------------
 (56.5, 'wiki', 'ad', {'grade': 'sepia', 'motion': 'down'}),
 (58.4, 'word', '$4.00', {'small': 'for one hour of your time', 'color': 'white', 'sfx': 'bell'}),
 (59.7, 'img',  'old wall clock black and white dark', {'grade': 'ink', 'motion': 'in'}),
 (61.4, 'clip', 'MDE:180', {'grade': 'sepia', 'motion': 'in'}),
 (63.2, 'clip', 'MDE:204', {'grade': 'sepia'}),
 (64.45,'gfx',  'counter', {'text': '40', 'sub': 'MEN SHOWED UP', 'sfx': 'hit'}),
 (66.1, 'img',  '1960s men group portrait black and white photo', {'grade': 'ink', 'motion': 'right'}),
 (68.0, 'img',  '1960s teacher classroom chalkboard black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (68.7, 'img',  '1960s engineer drafting table black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (69.8, 'img',  '1960s factory laborer worker black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (71.2, 'clip', 'MDE:36', {'grade': 'ink'}),
 (73.2, 'clip', 'MDE:84', {'grade': 'ink'}),
 (74.7, 'clip', 'MDE:126', {'grade': 'ink'}),
 (76.2, 'clip', 'MDE:804', {'grade': 'sepia', 'motion': 'in', 'sfx': 'glitch'}),
 (78.0, 'clip', 'MDE:362', {'grade': 'ink', 'motion': 'in'}),
 (80.55,'clip', 'MDE:139', {'grade': 'ink'}),
 (81.6, 'clip', 'MDE:408', {'grade': 'cold', 'motion': 'in'}),
 (83.2, 'clip', 'MDE:144', {'grade': 'ink', 'motion': 'in'}),
 (85.1, 'clip', 'MDE:216', {'grade': 'ink'}),
 (86.6, 'clip', 'MDE:235', {'grade': 'red', 'motion': 'left'}),
 (88.0, 'gfx',  'shockpanel', {'mode': 'reveal'}),
 (89.3, 'gfx',  'shockpanel', {'mode': 'sweep'}),
 (91.0, 'gfx',  'voltsteps', {}),
 (94.0, 'clip', 'MDE:234', {'grade': 'red', 'motion': 'right'}),
 (94.9, 'gfx',  'shockpanel', {'mode': 'label', 'group': 0}),
 (96.2, 'clip', 'MDE:240', {'grade': 'red', 'motion': 'in'}),
 (97.5, 'gfx',  'shockpanel', {'mode': 'label', 'group': 6}),
 (99.0, 'gfx',  'shockpanel', {'mode': 'zoomLast'}),
 (100.5,'word', 'XXX', {'bg': 'laser', 'sfx': 'shock'}),
 (102.9,'clip', 'MDE:205', {'grade': 'sepia'}),
 (103.5,'word', 'WRONG', {'small': 'every', 'color': 'white', 'sfx': 'buzz'}),
 (104.6,'gfx',  'shockpanel', {'mode': 'stepUp', 'sfx': 'click'}),
 (106.2,'gfx',  'voltmeter', {'value': 75, 'sfx': 'buzz'}),
 (108.0,'clip', 'MDE:456', {'grade': 'ink', 'motion': 'in'}),
 (109.55,'gfx', 'voltmeter', {'value': 150, 'sfx': 'buzz'}),
 (110.9,'clip', 'MDE:468', {'grade': 'red', 'motion': 'in'}),
 (112.9,'gfx',  'voltmeter', {'value': 300, 'sfx': 'shock'}),
 (114.2,'img',  'fist pounding on wall dark black and white', {'grade': 'ink', 'motion': 'shake', 'sfx': 'thuds'}),
 (116.2,'clip', 'MDE:408', {'grade': 'cold', 'motion': 'out'}),
 (117.9,'clip', 'MDE:600', {'grade': 'cold', 'motion': 'in', 'sfx': 'heartbeat'}),
 (120.7,'clip', 'MDE:558', {'grade': 'ink', 'motion': 'in'}),
 (122.7,'clip', 'MDE:510', {'grade': 'ink', 'motion': 'shake'}),
 (124.0,'clip', 'MDE:648', {'grade': 'gray'}),
 (125.4,'clip', 'MDE:186', {'grade': 'gray', 'motion': 'in'}),
 (127.0,'type', 'FOUR SENTENCES', {'sub': 'THE PRODS', 'bg': 'MDE:654'}),
 (129.5,'type', '"PLEASE CONTINUE."', {'sub': 'PROD 1', 'bg': 'MDE:552'}),
 (131.2,'type', '"THE EXPERIMENT REQUIRES THAT YOU CONTINUE."', {'sub': 'PROD 2', 'bg': 'MDE:541'}),
 (134.3,'type', '"IT IS ABSOLUTELY ESSENTIAL THAT YOU CONTINUE."', {'sub': 'PROD 3', 'bg': 'MDE:660'}),
 (138.0,'type', '"YOU HAVE NO OTHER CHOICE."', {'sub': 'PROD 4', 'bg': 'MDE:678'}),
 (140.0,'word', 'YOU MUST GO ON.', {'bg': 'MDE:192', 'sfx': 'boom'}),
 (142.9,'clip', 'MDE:462', {'grade': 'ink', 'motion': 'in'}),
 (143.9,'gfx',  'voltmeter', {'value': 300, 'sfx': 'buzz'}),
 (145.2,'gfx',  'counter', {'text': '26 / 40', 'sub': 'WENT FURTHER'}),
 (148.0,'word', '65%', {'bg': 'laser', 'sfx': 'impact'}),
 (149.0,'gfx',  'shockpanel', {'mode': 'cascadeAll', 'sfx': 'clicksAll'}),
 # ---------------- BRIDGE ----------------
 (152.8,'img',  'man whispering secret in ear dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (154.4,'word', '65%', {'small': 'what nobody tells you about the', 'color': 'white'}),
 (156.1,'clip', 'MDE:565', {'grade': 'ink', 'motion': 'in'}),
 (157.7,'clip', 'MDE:528', {'grade': 'red', 'motion': 'in'}),
 (160.0,'clip', 'MDE:700', {'grade': 'gray', 'motion': 'in'}),
 (162.9,'img',  'office meeting boss table dark illustration', {'grade': 'ink', 'motion': 'right'}),
 (164.3,'clip', 'WAY:192', {'grade': 'ink'}),
 (166.1,'word', 'JUST DO IT.', {'small': 'your boss says', 'color': 'white'}),
 (167.1,'type', '"I\'LL TAKE RESPONSIBILITY."', {'bg': 'WAY:198'}),
 (169.0,'clip', 'EIC:91', {'grade': 'ink', 'motion': 'in'}),
 (170.8,'clip', 'NUR:300', {'grade': 'ink', 'motion': 'in'}),
 (172.5,'clip', 'EIC:30', {'grade': 'ink', 'motion': 'in'}),
 (175.3,'type', '"I WAS ONLY FOLLOWING ORDERS."', {'bg': 'EIC:301', 'sfx': 'boom_end'}),
 (178.3,'clip', 'EIC:421', {'grade': 'ink', 'motion': 'in'}),
 (179.5,'clip', 'NUR:3480', {'grade': 'ink', 'motion': 'in'}),
 (180.55,'img', 'human brain wires circuit dark red illustration', {'grade': 'red', 'motion': 'in', 'sfx': 'glitch'}),
 (182.9,'word', '3 LEVELS', {'bg': 'laser', 'sfx': 'impact'}),
 (185.8,'img',  'surreal dark staircase three steps illustration', {'grade': 'ink', 'motion': 'up'}),
 (188.0,'img',  'empty hospital corridor night black and white', {'grade': 'cold', 'motion': 'in'}),
 # ---------------- LEVEL 1 ----------------
 (190.62,'card','The Costume', {'label': 'Level', 'num': '#1', 'icon': 'mask'}),
 (193.4,'img',  'stranger in hat and coat silhouette street night', {'grade': 'ink', 'motion': 'in'}),
 (195.6,'img',  'faceless businessman suit dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (196.7,'img',  'white lab coat hanging on hook dark', {'grade': 'gray', 'motion': 'up'}),
 (199.0,'clip', 'MDE:187', {'grade': 'gray', 'motion': 'in'}),
 (200.5,'img',  'Yale University seal emblem', {'grade': 'cold', 'motion': 'in'}),
 (202.0,'img',  'vintage clipboard with paper black and white', {'grade': 'ink', 'motion': 'in'}),
 (203.65,'img', 'authority figure silhouette judge dark illustration', {'grade': 'red', 'motion': 'in'}),
 (206.4,'img',  'police badge close up black and white', {'grade': 'ink', 'motion': 'in'}),
 (207.25,'img', 'judge gavel black and white dark', {'grade': 'ink', 'motion': 'in'}),
 (207.8,'img',  'military medals on uniform close up black and white', {'grade': 'ink', 'motion': 'in'}),
 (209.1,'img',  'empty suit hanging dark room', {'grade': 'ink', 'motion': 'in'}),
 (210.7,'img',  'cut puppet strings marionette dark illustration', {'grade': 'red', 'motion': 'down'}),
 (212.7,'wiki', 'milgram', {'grade': 'ink', 'motion': 'in'}),
 (214.2,'clip', 'MDE:876', {'grade': 'ink'}),
 # ---------------- LEVEL 2 ----------------
 (216.84,'card','The Staircase', {'label': 'Level', 'num': '#2', 'icon': 'stairs'}),
 (219.9,'clip', 'MDE:240', {'grade': 'red', 'motion': 'left'}),
 (221.4,'gfx',  'voltmeter', {'value': 450, 'sfx': 'shock'}),
 (222.9,'gfx',  'staircase', {'marks': [225.2, 227.0, 228.5], 'sfx': 'stepclicks'}),
 (230.5,'img',  'person climbing endless stairs dark surreal illustration', {'grade': 'ink', 'motion': 'up'}),
 (232.0,'clip', 'MDE:450', {'grade': 'ink', 'motion': 'in'}),
 (233.6,'img',  'escher impossible staircase illustration', {'grade': 'ink', 'motion': 'in'}),
 (236.0,'gfx',  'staircase', {'marks': [], 'all': True}),
 (238.7,'clip', 'MDE:535', {'grade': 'red', 'motion': 'shake'}),
 (241.2,'clip', 'MDE:559', {'grade': 'ink', 'motion': 'in'}),
 (242.3,'gfx',  'shockpanel', {'mode': 'cascade', 'sfx': 'clicks'}),
 (244.9,'img',  'man climbing stairs into darkness silhouette', {'grade': 'ink', 'motion': 'up'}),
 # ---------------- LEVEL 3 ----------------
 (247.98,'card','The Vanishing Self', {'label': 'Level', 'num': '#3', 'icon': 'ghost'}),
 (251.3,'img',  'person dissolving into smoke dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (252.5,'img',  'finger on lips silence black and white dark', {'grade': 'ink', 'motion': 'in'}),
 (254.4,'clip', 'MDE:133', {'grade': 'ink', 'motion': 'in'}),
 (256.2,'img',  'man disintegrating into particles dark', {'grade': 'ink', 'motion': 'in'}),
 (258.7,'clip', 'MDE:553', {'grade': 'gray', 'motion': 'in'}),
 (261.3,'type', '"THE EXPERIMENT REQUIRES IT."', {'bg': 'MDE:666'}),
 (264.0,'word', 'RESPONSIBILITY', {'small': 'and', 'color': 'white'}),
 (265.7,'img',  'atlas carrying heavy weight on shoulders dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (267.7,'img',  'smoke rising upward dark', {'grade': 'ink', 'motion': 'up'}),
 (269.3,'clip', 'MDE:516', {'grade': 'ink', 'motion': 'in'}),
 (271.4,'clip', 'MDE:655', {'grade': 'gray', 'motion': 'in'}),
 (274.6,'wiki', 'milgram', {'grade': 'ink', 'motion': 'left'}),
 (275.5,'word', 'THE AGENTIC STATE', {'small': 'Milgram called it'}),
 (277.7,'img',  'puppet master hand controlling marionette strings dark illustration', {'grade': 'red', 'motion': 'in'}),
 (279.0,'img',  'marionette puppet man dark', {'grade': 'ink', 'motion': 'in'}),
 (280.9,'wiki', 'scream', {'grade': 'color', 'motion': 'in'}),
 (284.4,'img',  'vintage surgical instruments black and white', {'grade': 'ink', 'motion': 'right'}),
 (287.1,'clip', 'MDE:230', {'grade': 'red', 'motion': 'in'}),
 # ---------------- HOFLING ----------------
 (288.4,'type', '1966', {'sub': 'FIVE YEARS LATER'}),
 (289.5,'img',  'vintage hospital ward 1960s black and white photo', {'grade': 'ink', 'motion': 'left'}),
 (290.5,'img',  'empty hospital corridor night black and white photo', {'grade': 'cold', 'motion': 'in'}),
 (293.5,'type', 'CHARLES K. HOFLING', {'sub': 'PSYCHIATRIST', 'bg': 'img:1960s psychiatrist doctor portrait black and white photo'}),
 (295.7,'gfx',  'shockpanel', {'mode': 'reveal'}),
 (297.1,'img',  '1960s nurse hospital night shift black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (299.1,'gfx',  'counter', {'text': '22', 'sub': 'NIGHT SHIFTS'}),
 (300.5,'img',  'nurse station night 1960s black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (301.8,'img',  'hospital ward beds 1960s black and white photo', {'grade': 'ink', 'motion': 'left'}),
 (303.6,'clip', 'WAY:204', {'grade': 'ink', 'sfx': 'ring'}),
 (305.9,'clip', 'WAY:430', {'grade': 'ink', 'motion': 'in'}),
 (306.6,'type', '"THIS IS DR. SMITH."', {'bg': 'WAY:434'}),
 (308.0,'clip', 'WAY:211', {'grade': 'ink', 'motion': 'in'}),
 (309.5,'img',  'hospital patient in bed 1960s black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (309.9,'word', '20 MG', {'color': 'white', 'sfx': 'whoosh'}),
 (311.1,'gfx',  'pilllabel', {'mode': 'show'}),
 (313.2,'gfx',  'pilllabel', {'mode': 'max'}),
 (317.4,'word', 'NO LAB COAT', {'color': 'white', 'sfx': 'whoosh'}),
 (318.9,'word', 'NO YALE', {'color': 'white', 'sfx': 'whoosh'}),
 (320.1,'word', 'NO CLIPBOARD', {'color': 'white', 'sfx': 'whoosh'}),
 (321.5,'clip', 'WAY:217', {'grade': 'ink', 'motion': 'in'}),
 (323.1,'clip', 'WAY:437', {'grade': 'ink', 'motion': 'in'}),
 (323.8,'word', '3 RULES BROKEN', {'small': 'at once', 'sfx': 'impact'}),
 (327.4,'gfx',  'counter', {'text': '21 / 22', 'sub': 'NURSES'}),
 (329.2,'img',  'vintage hospital medicine cabinet black and white', {'grade': 'ink', 'motion': 'in'}),
 (331.0,'img',  'nurse filling syringe vintage black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (331.9,'img',  'hand grabbing wrist stop dark', {'grade': 'ink', 'motion': 'in'}),
 (334.2,'img',  'patient sleeping hospital bed black and white', {'grade': 'cold', 'motion': 'in'}),
 (335.4,'gfx',  'counter', {'text': '21 / 22', 'sub': 'WERE READY', 'color': 'red', 'sfx': 'boom'}),
 (338.85,'clip','WAY:529', {'grade': 'ink', 'motion': 'in'}),
 (340.8,'img',  'faceless person fading away dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (342.0,'clip', 'MDE:60', {'grade': 'ink', 'motion': 'in'}),
 (344.2,'clip', 'WAY:428', {'grade': 'ink', 'motion': 'in'}),
 (346.5,'clip', 'WAY:221', {'grade': 'red', 'motion': 'in'}),
 (348.5,'clip', 'WAY:516', {'grade': 'ink', 'motion': 'up'}),
 (350.2,'img',  'hands in surgical gloves dark', {'grade': 'ink', 'motion': 'in'}),
 (353.7,'word', 'FREEZE', {'small': "here's the part that should", 'color': 'white', 'sfx': 'impact'}),
 (356.2,'img',  'nurses group 1960s black and white photo', {'grade': 'ink', 'motion': 'right'}),
 (358.4,'img',  'nursing students classroom 1960s black and white photo', {'grade': 'ink', 'motion': 'in'}),
 (360.3,'img',  'vintage questionnaire paper form', {'grade': 'sepia', 'motion': 'down'}),
 (362.8,'word', '"I\'D REFUSE."', {'small': 'almost all of them said', 'color': 'white'}),
 (366.3,'img',  'old rule book open dark', {'grade': 'ink', 'motion': 'in'}),
 (367.9,'gfx',  'pilllabel', {'mode': 'lethal'}),
 (371.0,'img',  'woman looking into broken mirror dark', {'grade': 'ink', 'motion': 'in'}),
 (373.4,'clip', 'MDE:90', {'grade': 'ink'}),
 # ---------------- THE MISTAKE ----------------
 (376.3,'img',  'audience silhouettes watching dark', {'grade': 'ink', 'motion': 'in'}),
 (377.8,'img',  'hand pointing finger accusing dark illustration', {'grade': 'red', 'motion': 'in'}),
 (380.0,'gfx',  'split', {'left': 'THE GOOD ONES', 'right': 'THE MONSTERS'}),
 (383.0,'img',  'man walking away into light silhouette', {'grade': 'ink', 'motion': 'in'}),
 (385.1,'img',  'monster shadow silhouette dark illustration', {'grade': 'red', 'motion': 'in'}),
 (387.4,'img',  '1960s psychiatrists conference black and white photo', {'grade': 'ink', 'motion': 'left'}),
 (389.7,'clip', 'MDE:686', {'grade': 'ink', 'motion': 'in'}),
 (392.0,'clip', 'MDE:811', {'grade': 'ink'}),
 (394.1,'img',  'crystal ball fortune teller dark vintage', {'grade': 'cold', 'motion': 'in'}),
 (396.2,'gfx',  'counter', {'text': '1 / 100', 'sub': 'THEY PREDICTED'}),
 (398.7,'img',  'sinister smile dark illustration', {'grade': 'red', 'motion': 'in'}),
 (399.6,'img',  'broken man shattered portrait dark', {'grade': 'ink', 'motion': 'in'}),
 (400.9,'gfx',  'voltmeter', {'value': 450}),
 (403.9,'gfx',  'prediction', {'actualAt': 405.9}),
 # ---------------- THE TWIST ----------------
 (410.2,'word', 'THE TWIST', {'bg': 'laser', 'sfx': 'impact'}),
 (411.9,'img',  'shattered mirror reflection dark', {'grade': 'ink', 'motion': 'in'}),
 (415.6,'gfx',  'counter', {'text': '26', 'sub': 'WENT TO THE END'}),
 (417.6,'clip', 'MDE:199', {'grade': 'ink', 'motion': 'in'}),
 (419.4,'clip', 'MDE:560', {'grade': 'ink', 'motion': 'in'}),
 (422.0,'img',  'old handwritten notes notebook black and white', {'grade': 'sepia', 'motion': 'left'}),
 (423.4,'clip', 'MDE:506', {'grade': 'ink', 'motion': 'in'}),
 (425.9,'clip', 'NAR:425', {'grade': 'ink', 'motion': 'shake'}),
 (426.7,'clip', 'NAR:504', {'grade': 'ink', 'motion': 'in'}),
 (427.7,'img',  'biting lip close up dark', {'grade': 'red', 'motion': 'in'}),
 (430.4,'gfx',  'counter', {'text': '14', 'sub': 'NERVOUS LAUGHTER'}),
 (431.3,'clip', 'MDE:451', {'grade': 'ink', 'motion': 'in'}),
 (433.4,'img',  'creepy smiling mask dark', {'grade': 'red', 'motion': 'in'}),
 (434.6,'img',  'pressure gauge needle red zone', {'grade': 'red', 'motion': 'in'}),
 (437.7,'clip', 'NAR:480', {'grade': 'ink', 'motion': 'shake'}),
 (439.4,'clip', 'NAR:496', {'grade': 'ink'}),
 (440.3,'clip', 'MDE:569', {'grade': 'ink'}),
 (442.3,'clip', 'MDE:631', {'grade': 'ink'}),
 (443.3,'clip', 'MDE:672', {'grade': 'gray', 'motion': 'in'}),
 (444.4,'clip', 'MDE:561', {'grade': 'ink', 'motion': 'in'}),
 (445.8,'clip', 'MDE:529', {'grade': 'red', 'motion': 'in', 'sfx': 'clickbuzz'}),
 (447.2,'gfx',  'shockpanel', {'mode': 'stepUp', 'sfx': 'click'}),
 (449.7,'word', 'READ THAT AGAIN.', {'color': 'white', 'sfx': 'glitch'}),
 (451.6,'img',  'closed eye close up black and white', {'grade': 'ink', 'motion': 'in'}),
 (453.9,'img',  'wide open eye close up dark', {'grade': 'red', 'motion': 'in'}),
 (455.6,'img',  'screaming man dark painting', {'grade': 'red', 'motion': 'shake'}),
 (456.7,'clip', 'MDE:532', {'grade': 'ink', 'motion': 'in'}),
 (458.8,'clip', 'MDE:690', {'grade': 'ink', 'motion': 'in'}),
 (461.9,'img',  'blindfolded man dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (463.5,'img',  'person watching screen alone dark room silhouette', {'grade': 'cold', 'motion': 'in'}),
 (465.8,'img',  'anatomical heart dark red illustration', {'grade': 'red', 'motion': 'in'}),
 (468.0,'img',  'cracked shield dark', {'grade': 'ink', 'motion': 'in'}),
 # ---------------- THE REFRAME ----------------
 (470.36,'word','THE REFRAME', {'bg': 'laser', 'sfx': 'impact'}),
 (473.2,'img',  'old light switch off dark', {'grade': 'ink', 'motion': 'in', 'sfx': 'click_at:474.0'}),
 (474.5,'img',  'angel and devil on shoulders dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (475.9,'word', 'IT OUTRANKS THEM.', {'sfx': 'boom'}),
 (477.8,'clip', 'MDE:701', {'grade': 'gray', 'motion': 'in'}),
 (480.4,'clip', 'WAY:432', {'grade': 'ink', 'motion': 'in'}),
 (481.7,'img',  'vintage radio microphone broadcast black and white', {'grade': 'ink', 'motion': 'in'}),
 (484.2,'img',  'man shouting megaphone dark', {'grade': 'red', 'motion': 'shake'}),
 (485.4,'clip', 'MDE:512', {'grade': 'ink', 'motion': 'in'}),
 (486.4,'clip', 'MDE:528', {'grade': 'red', 'motion': 'in'}),
 (488.8,'img',  'monster shadow on wall behind man dark', {'grade': 'ink', 'motion': 'in'}),
 (490.6,'img',  'werewolf transformation shadow dark illustration', {'grade': 'red', 'motion': 'in'}),
 (492.5,'clip', 'MDE:463', {'grade': 'ink', 'motion': 'in'}),
 (495.5,'clip', 'MDE:228', {'grade': 'red', 'motion': 'in', 'sfx': 'clickbuzz'}),
 # ---------------- TWO QUESTIONS ----------------
 (498.7,'word', '2 QUESTIONS', {'small': 'that break the spell', 'bg': 'laser', 'sfx': 'impact'}),
 (502.4,'img',  'hourglass sand dark', {'grade': 'ink', 'motion': 'in'}),
 (504.5,'word', 'YES.', {'small': 'the next small', 'color': 'white'}),
 (506.8,'clip', 'MDE:864', {'grade': 'ink', 'motion': 'in'}),
 (511.1,'img',  'hand raised stop gesture dark', {'grade': 'ink', 'motion': 'in'}),
 (512.9,'gfx',  'staircase', {'marks': [], 'stopNext': True}),
 (514.9,'img',  'small notebook in coat pocket vintage', {'grade': 'sepia', 'motion': 'in'}),
 (518.46,'card','Would I do this if nobody asked me to?', {'label': 'Question', 'num': '#1', 'icon': 'question'}),
 (523.0,'img',  'empty room single chair spotlight dark', {'grade': 'ink', 'motion': 'in'}),
 (525.8,'word', 'NO BOSS', {'color': 'white', 'sfx': 'whoosh'}),
 (527.6,'word', 'NO UNIFORM', {'color': 'white', 'sfx': 'whoosh'}),
 (528.9,'word', 'NO DOCTOR', {'color': 'white', 'sfx': 'whoosh'}),
 (531.8,'img',  'man sitting alone dark room window light', {'grade': 'ink', 'motion': 'in'}),
 (533.9,'clip', 'MDE:230', {'grade': 'red', 'motion': 'in'}),
 (535.6,'clip', 'MDE:134', {'grade': 'ink', 'motion': 'in'}),
 (537.2,'img',  'marionette strings attached to hands dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (538.7,'clip', 'WAY:517', {'grade': 'cold', 'motion': 'up', 'sfx': 'static'}),
 (540.96,'card','Who actually faces the consequence?', {'label': 'Question', 'num': '#2', 'icon': 'bolt'}),
 (545.7,'clip', 'MDE:528', {'grade': 'ink', 'motion': 'in', 'sfx': 'clickbuzz'}),
 (548.4,'clip', 'MDE:534', {'grade': 'red', 'motion': 'shake', 'sfx': 'shock'}),
 (551.1,'clip', 'WAY:194', {'grade': 'ink', 'motion': 'in'}),
 (552.8,'img',  'soldier silhouette battlefield smoke dark', {'grade': 'red', 'motion': 'in'}),
 (555.0,'img',  'man fading into shadow dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (559.5,'img',  'small footsteps in snow dark', {'grade': 'cold', 'motion': 'up'}),
 (561.7,'clip', 'WAY:190', {'grade': 'ink', 'motion': 'in'}),
 (563.2,'type', '"JUST BACKDATE IT."', {'bg': 'img:vintage rubber date stamp on document'}),
 (564.1,'type', '"I\'LL TAKE RESPONSIBILITY."', {'bg': 'WAY:197'}),
 (565.9,'word', "HE WON'T.", {'sfx': 'boom'}),
 (567.2,'img',  'phishing email on laptop screen dark', {'grade': 'cold', 'motion': 'in'}),
 (570.1,'img',  'urgent bank transfer warning red screen', {'grade': 'red', 'motion': 'in'}),
 (573.3,'clip', 'WAY:220', {'grade': 'red', 'motion': 'in'}),
 (575.6,'word', 'THE PAUSE', {'small': 'is the weapon', 'sfx': 'impact'}),
 (578.1,'img',  'dominoes falling in a row dark', {'grade': 'ink', 'motion': 'left'}),
 (580.5,'img',  'stacked wooden blocks tower dark', {'grade': 'ink', 'motion': 'up'}),
 (583.1,'img',  'hand stopping falling dominoes', {'grade': 'ink', 'motion': 'in'}),
 (585.4,'gfx',  'staircase', {'marks': [], 'breakAt': 585.4, 'sfx': 'impact'}),
 (588.1,'img',  'man standing up speaking in meeting illustration', {'grade': 'ink', 'motion': 'in'}),
 (590.8,'clip', 'WAY:196', {'grade': 'ink'}),
 (592.5,'clip', 'WAY:117', {'grade': 'ink', 'motion': 'in'}),
 (594.1,'gfx',  'staircase', {'marks': [], 'named': True}),
 (596.3,'img',  'man walking away from staircase silhouette', {'grade': 'ink', 'motion': 'in'}),
 (598.0,'img',  'broken chains dark', {'grade': 'red', 'motion': 'in'}),
 # ---------------- THE LEVER BREAKS ----------------
 (600.8,'word', 'THE LEVER BREAKS', {'small': 'but', 'bg': 'MDE:529', 'sfx': 'impact'}),
 (603.1,'wiki', 'milgram', {'grade': 'ink', 'motion': 'right'}),
 (605.7,'clip', 'MDE:877', {'grade': 'ink', 'motion': 'in'}),
 (608.6,'clip', 'MDE:91', {'grade': 'ink', 'motion': 'in'}),
 (611.0,'word', 'REFUSE', {'small': 'two fellow teachers', 'color': 'white'}),
 (612.1,'gfx',  'variations', {'step': 1}),
 (614.8,'img',  'one red figure among gray crowd illustration', {'grade': 'color', 'motion': 'in'}),
 (618.3,'clip', 'WAY:219', {'grade': 'ink', 'motion': 'in'}),
 (621.2,'clip', 'MDE:542', {'grade': 'ink'}),
 (622.3,'gfx',  'variations', {'step': 2}),
 (624.9,'wiki', 'yale', {'grade': 'ink', 'motion': 'left'}),
 (627.3,'img',  'shabby run down office 1960s black and white', {'grade': 'sepia', 'motion': 'in'}),
 (630.0,'gfx',  'variations', {'step': 3}),
 (632.3,'word', 'SAME MACHINE', {'bg': 'MDE:236', 'color': 'white'}),
 (633.9,'word', 'SAME VOLTS', {'bg': 'MDE:240', 'color': 'white'}),
 (635.6,'word', 'SAME ORDINARY MEN', {'bg': 'MDE:96', 'color': 'white'}),
 (637.8,'img',  'white lab coat on hanger dark background', {'grade': 'gray', 'motion': 'in'}),
 (639.7,'clip', 'MDE:656', {'grade': 'gray', 'motion': 'in'}),
 (640.7,'img',  'crowd of people agreeing nodding illustration', {'grade': 'ink', 'motion': 'in'}),
 # ---------------- THE WARNING ----------------
 (642.86,'word','THE WARNING', {'bg': 'laser', 'sfx': 'impact'}),
 (644.7,'img',  'puppet breaking free cutting strings illustration', {'grade': 'red', 'motion': 'in'}),
 (646.7,'img',  'climber on mountain summit silhouette dark', {'grade': 'ink', 'motion': 'up'}),
 (648.0,'img',  'hourglass running out dark', {'grade': 'ink', 'motion': 'in'}),
 (649.1,'img',  'height measuring chart wall vintage', {'grade': 'sepia', 'motion': 'up'}),
 (651.7,'word', 'A SITUATION', {'small': "it's", 'color': 'white'}),
 (653.7,'img',  'long corridor many doors dark', {'grade': 'ink', 'motion': 'in'}),
 (655.1,'clip', 'MDE:409', {'grade': 'cold', 'motion': 'in'}),
 (656.9,'clip', 'MDE:97', {'grade': 'ink'}),
 (659.9,'img',  'two silhouettes standing side by side dark', {'grade': 'ink', 'motion': 'in'}),
 (662.0,'img',  'one person standing out from crowd red illustration', {'grade': 'color', 'motion': 'in'}),
 (664.0,'img',  'empty silhouette head dark illustration', {'grade': 'ink', 'motion': 'in'}),
 (667.1,'img',  'two people walking together silhouette black and white', {'grade': 'ink', 'motion': 'left'}),
 (670.0,'img',  'friends standing together silhouette dusk', {'grade': 'ink', 'motion': 'in'}),
 (671.8,'gfx',  'pilllabel', {'mode': 'show'}),
 (674.4,'word', 'THE NEXT SMALL YES', {'sfx': 'impact'}),
 (676.8,'img',  'hand offering pen to sign contract dark', {'grade': 'ink', 'motion': 'in'}),
 (678.8,'img',  'city street at night 1960s black and white', {'grade': 'ink', 'motion': 'left'}),
 (681.0,'clip', 'MDE:188', {'grade': 'gray', 'motion': 'in'}),
 (684.1,'clip', 'MDE:661', {'grade': 'gray', 'motion': 'in'}),
 (686.3,'word', 'YES.', {'small': 'it only needs your next small', 'sfx': 'boom'}),
 (689.7,'clip', 'MDE:135', {'grade': 'ink', 'motion': 'in'}),
 (691.3,'clip', 'MDE:189', {'grade': 'gray', 'motion': 'in'}),
 (692.9,'clip', 'EIC:425', {'grade': 'ink', 'motion': 'in'}),
 (693.7,'clip', 'WAY:222', {'grade': 'ink', 'motion': 'in'}),
 (694.8,'type', '"I TAKE THE RESPONSIBILITY."', {'bg': 'MDE:662'}),
 (697.6,'gfx',  'shockpanel', {'mode': 'reveal'}),
 (699.2,'clip', 'MDE:228', {'grade': 'red', 'motion': 'in', 'sfx': 'clickbuzz'}),
 (699.6,'img',  'crowd of ordinary people 1960s black and white photo', {'grade': 'ink', 'motion': 'left'}),
 (701.9,'card', 'The Law of Power They Never Teach You', {'label': 'Next', 'num': '', 'icon': 'eye'}),
 (706.0,'img',  'glowing light bulb in dark room', {'grade': 'color', 'motion': 'in'}),
 (708.3,'img',  'man falling into darkness silhouette', {'grade': 'ink', 'motion': 'down'}),
 (709.7,'black', '', {}),
]

END = 711.5  # final frame (seconds): 2s tail after the last word

# Caption corrections for ASR mistakes (matched on the word, punctuation preserved)
FIXES = {'Hoefling,': 'Hofling,', 'Hoefling': 'Hofling', 'Berger,': 'Burger,', 'Astraten.': 'Astroten.',
         'saved': 'safe', 'vaults.': 'volts.', 'revel': 'rebel', 'psychiatrist': 'psychiatrists'}

# ---------------------------------------------------------------------------
# Verified shot times (real seconds, from shot detection). These supersede the
# clip specs above, which were read off mislabeled contact sheets.
# beat_time -> 'SRC:seconds'
CLIPFIX = {
    0.55: 'MDE:359.75', 1.5: 'MDE:214', 4.7: 'MDE:526', 5.5: 'MDE:592', 6.3: 'MDE:507',
    12.88: 'MDE:2', 26.9: 'MDE:528', 29.1: 'MDE:362', 29.9: 'MDE:534.5', 36.3: 'MDE:134.5',
    37.4: 'MDE:220', 42.88: 'MDE:860', 61.4: 'MDE:206', 63.2: 'MDE:35', 71.2: 'MDE:50',
    73.2: 'MDE:85', 74.7: 'MDE:118', 76.2: 'MDE:804.8', 78.0: 'MDE:339', 80.55: 'MDE:128',
    81.6: 'MDE:665', 83.2: 'MDE:142', 85.1: 'MDE:342.5', 86.6: 'MDE:230', 94.0: 'MDE:234',
    96.2: 'MDE:240', 102.9: 'MDE:207', 108.0: 'MDE:446.8', 110.9: 'MDE:470', 116.2: 'MDE:729.5',
    117.9: 'MDE:733', 120.7: 'MDE:550.5', 122.7: 'MDE:518', 124.0: 'MDE:669', 125.4: 'MDE:183',
    142.9: 'MDE:460', 156.1: 'MDE:560', 157.7: 'MDE:527', 160.0: 'MDE:705', 164.3: 'WAY:190',
    169.0: 'EIC:121', 172.5: 'EIC:250', 178.3: 'EIC:330', 199.0: 'MDE:195', 214.2: 'MDE:875',
    219.9: 'MDE:244', 232.0: 'MDE:450', 238.7: 'MDE:535.5', 241.2: 'MDE:465', 254.4: 'MDE:350',
    258.7: 'MDE:672', 269.3: 'MDE:509', 271.4: 'MDE:750', 287.1: 'MDE:530', 303.6: 'WAY:219.5',
    305.9: 'WAY:209', 308.0: 'WAY:212', 321.5: 'WAY:221', 323.1: 'WAY:245', 338.85: 'WAY:542',
    342.0: 'MDE:10', 344.2: 'WAY:199', 346.5: 'WAY:223', 348.5: 'WAY:517', 373.4: 'MDE:95',
    389.7: 'MDE:828', 392.0: 'MDE:809', 417.6: 'MDE:520', 419.4: 'MDE:462', 423.4: 'MDE:510',
    425.9: 'NAR:428', 426.7: 'NAR:424', 431.3: 'MDE:451', 437.7: 'NAR:448', 439.4: 'NAR:482',
    440.3: 'MDE:595', 442.3: 'MDE:467', 443.3: 'MDE:555.5', 444.4: 'MDE:552.5', 445.8: 'MDE:531',
    456.7: 'MDE:503', 458.8: 'MDE:937', 477.8: 'MDE:712', 480.4: 'MDE:343', 485.4: 'MDE:512',
    486.4: 'MDE:532', 492.5: 'MDE:463', 495.5: 'MDE:225', 506.8: 'MDE:880', 533.9: 'MDE:236',
    535.6: 'MDE:134.6', 538.7: 'WAY:518', 545.7: 'MDE:526', 548.4: 'MDE:534.6', 551.1: 'WAY:192',
    561.7: 'WAY:189.5', 573.3: 'WAY:220', 590.8: 'WAY:200', 592.5: 'WAY:214', 605.7: 'MDE:890',
    608.6: 'MDE:34', 618.3: 'WAY:240', 621.2: 'MDE:515', 639.7: 'MDE:200', 655.1: 'MDE:416',
    656.9: 'MDE:610', 681.0: 'MDE:186', 684.1: 'MDE:760', 689.7: 'MDE:353', 691.3: 'MDE:198',
    692.9: 'EIC:335', 693.7: 'WAY:222', 699.2: 'MDE:528',
    # stills replaced by real period footage
    24.28: 'NAR:54', 25.5: 'NAR:63', 309.5: 'NAR:469', 334.2: 'NAR:488', 331.9: 'NAR:357',
}
# beat_time -> background clip for titles / typewriter / carousel
BGFIX = {
    7.3: 'MDE:534.6', 34.3: 'MDE:529', 51.3: 'WAY:220', 53.9: 'MDE:870', 127.0: 'MDE:701',
    129.5: 'MDE:514', 131.2: 'MDE:540', 134.3: 'MDE:554.6', 138.0: 'MDE:742', 140.0: 'MDE:190',
    167.1: 'WAY:196', 175.3: 'EIC:60', 261.3: 'MDE:679', 306.6: 'WAY:238', 564.1: 'WAY:197',
    600.8: 'MDE:533', 632.3: 'MDE:236', 633.9: 'MDE:360', 635.6: 'MDE:60', 694.8: 'MDE:701',
}
# corrections after reviewing the first frame of every clip (review/clipcheck_*.png)
CLIPFIX.update({
    125.4: 'MDE:545', 164.3: 'WAY:194.3', 323.1: 'WAY:216', 344.2: 'NAR:674', 495.5: 'MDE:532.5',
    551.1: 'MDE:705', 561.7: 'WAY:201', 590.8: 'NAR:686', 618.3: 'WAY:204.3', 681.0: 'MDE:778',
    691.3: 'MDE:1065', 692.9: 'NUR:3482',
})
BGFIX.update({306.6: 'WAY:224'})
B = [(t, 'clip' if t in CLIPFIX else k, CLIPFIX.get(t, a), {**o, 'bg': BGFIX[t]} if t in BGFIX else o)
     for (t, k, a, o) in B]
